name: novelist
version: '0.0.0.1'
synopsis: Initial project template from stack
description: Some description here.
category: Other
author: Konrad Gądek
maintainer: kgadek@gmail.com
copyright: 2016, Konrad Gądek
license: BSD3
github: kgadek/novelist


dependencies:
  - base >= 4.7 && < 5

library:
  source-dirs: src
  exposed-modules:
    - System.Novelist
    - System.Novelist.NovelistF
    - System.Novelist.Novelist
  dependencies:
    - directory
    - fclabels
    - mtl
    - transformers
    - deepseq
    - recursion-schemes
    - free

executables:
  novelist-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - novelist

tests:
  novelist-test:
    main: Main.hs
    source-dirs:
      - test
      - qc-gen
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - novelist
      - hspec
      - hspec-core
      - HUnit
      - QuickCheck
      - fclabels
      - free
      - recursion-schemes

benchmarks:
  novelist-criterion:
    main: Bench.hs
    source-dirs:
      - bench
      - qc-gen
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - novelist
      - criterion
      - QuickCheck
      - fclabels
      - deepseq
      - recursion-schemes
      - free
