resolver: lts-7.19

packages:
- '.'
- location:
    git: https://github.com/ekmett/recursion-schemes.git
    commit: cf30558c3da375868a54600c6f796d2c7cd60565
  extra-dep: true

extra-deps:
  - dump-core-0.1.3
  - freer-effects-0.3.0.0

flags: {}

extra-package-dbs: []
